# The app will need to use the coins: BTC, BCH, ETH and LTC
# the test wants the datas: 
  #ticker.low,   
  #ticker.high, 
  #ticker.vol, 
  #primeiros 20 itens de orderbook.asks
  #ultimos 20 itens de orderbook.bids

GET https://www.mercadobitcoin.net/api/BTC/ticker/
Accept: application/json

###
GET https://www.mercadobitcoin.net/api/BTC/orderbook/
Accept: application/json

###
GET https://www.mercadobitcoin.net/api/BTC/trades/
Accept: application/json
